### ISSUE TITLE
Chapter-oriented seeds

### ISSUE THREAD

**Issue by topepo** [tidymodels/TMwR#128]
Since we've been moving away from unusual numbers for seeds, it might be a good idea to number them by chapter. 

For example, the first seed in chapter 5 would be 501, chapter 11 starts with 1101, and so on.

**Comment by petehobo** [comment]
A couple of thoughts on this one - feel free to ignore me...

There are places your content relies on the existing seeds.  For example, the assertion in section 6.3 "in this case, no houses at all in the Landmark neighborhood were included in the training set" may not be true with a different seed.

Second, you'd want to be clear how the chapter-level seeds would work when referencing code from previous chapters.  For example, at the top of chapter 6: "This chapter uses the Ames housing data and the R objects created in the book so far, as summarized in Section 5.6.".  Would I use chapter 5 seeds or chapter 6 seeds when running that code for chapter 6?
