### ISSUE TITLE
Include code for maps in chapter 4.1

### ISSUE THREAD

**Issue by maxdrohde** [tidymodels/TMwR#132]
Chapter 4.1 includes various views of a map showing the neighborhoods in the Ames data set. However, I don't believe that the code to create these plots are included in the book.

I think it would be valuable to include the code for these plots -- even as an appendix.

**Comment by topepo** [comment]
The code is in the [`extras`](https://github.com/tidymodels/TMwR/blob/master/extras/ames_sf.R) directory. 

We put stuff there that is not in the day-to-day building of the book but we want public.
