### ISSUE TITLE
Definition and name change - Ames - gross living area = `Gr_Liv_Area`

### ISSUE THREAD

**Issue by bakergreg** [tidymodels/TMwR#148]
TMwR/06-feature-engineering.Rmd (first noticed here) 
It may continue through TMwR book, tidymodels and AmesHousing packages text and definitions.

## The problem
Misnamed feature definition: 

Change the name "general living area" to "gross living area" for variable (continuous, named `Gr_Liv_Area`)

## Reference 
Appraisal Institute's Dictionary of Real Estate 4th Edition: “Gross Living Area (GLA) – The total area of finished, above-grade residential space excluding unheated areas such as porches and balconies; the standard measure for determining the amount of space in residential properties.”

https://www.google.com/search?q=gross+living+area+definition
More info than you really need: https://www.appraisalinstitute.org/assets/1/7/Reducing_Liability.ppt

**Comment by juliasilge** [comment]
Ah, this is interesting @bakergreg. The data documentation [for where this data is sourced from](http://jse.amstat.org/v19n3/decock/DataDocumentation.txt) says this, which is consistent with those definitions:

> Gr Liv Area (Continuous): Above grade (ground) living area square feet

This is verbatim [what is in the AmesHousing package](https://github.com/topepo/AmesHousing/blob/master/R/ames_raw.R), and there is no reference to this variable in modeldata, so those packages should be fine. I think any edits only need to be made here in TMwR.

Sounds like we should make edits to change to "gross living area". 👍
