### ISSUE TITLE
Typo in Chapter 1?

### ISSUE THREAD

**Issue by petehobo** [tidymodels/TMwR#154]
In the table about the thought process for creating a model for the Chicago train data, the phrase "It seems like we should focus on a lot boosting iterations for that model." reads wrong to me.

I'd raise a pull request, but I'm not sure whether it should be "It seems like we should focus on a lot of boosting iterations for that model." or "It seems like we should focus a lot on boosting iterations for that model."

**Comment by juliasilge** [comment]
You are totally right @petehobo; thank you! 🙌
