### ISSUE TITLE
Slightly "off" figures

### ISSUE THREAD

**Issue by hfrick** [tidymodels/TMwR#158]
There are some figures which are not _quite_ right:
- The figure in 6.2 (`premade/recipes-process.svg`) is cut off on the right.
- The figures on model workflow in 8.1 (`premade/bad-workflow.svg` and `premade/proper-workflow.svg`): the text is not fully centred in the enclosing form.

**Comment by juliasilge** [comment]
Can you clarify what you are seeing, maybe with screenshots @hfrick? I am wondering if this is OS or browser related. Here is what I see:
![Screen Shot 2021-06-11 at 2 28 53 PM](https://user-images.githubusercontent.com/12505835/121745250-67913300-cac1-11eb-8c74-e3b63b36d797.png)
![Screen Shot 2021-06-11 at 2 29 02 PM](https://user-images.githubusercontent.com/12505835/121745296-695af680-cac1-11eb-9df9-0bb47a6d18d0.png)

**Comment by hfrick** [comment]
interesting! so this is what I see on ubuntu with firefox when I look at https://www.tmwr.org/:

![image](https://user-images.githubusercontent.com/12950918/121872879-af9c9980-ccfd-11eb-840b-6909ac77a8be.png)

![image](https://user-images.githubusercontent.com/12950918/121873191-073b0500-ccfe-11eb-9a8d-40b47fdc2400.png)

**Comment by hfrick** [comment]
when I (locally) open the `.svg` checked into the repo I see

![image](https://user-images.githubusercontent.com/12950918/121873781-a19b4880-ccfe-11eb-80ca-f516098d4c3a.png)

so the "g" of preprocessing in the recipes one is still cut off but a little less than in the browser. There are also _tiny_ differences for the workflow graphs but the "s" of Least squares estimation is touching the border in both.

**Comment by topepo** [comment]
@cderv Any ideas on this?

**Comment by cderv** [comment]
Nothing known that comes to mind. It looks not-cut when I open on chrome on Windows. Like Julia's screenshot.
It seems knitr is not responsible to generate the svg file and they are just included as is, right ? 

So maybe something related to CSS and browser handling of svg ?

On my computer, opening the local svg is also ok. Nothing is truncated.

**Comment by juliasilge** [comment]
We haven't gotten any other reports of this so let's close this and look into more if needed.
