### ISSUE TITLE
don't mention `step_mutate_at()`?

### ISSUE THREAD

**Issue by hfrick** [tidymodels/TMwR#159]
`dplyr::mutate_at()` has been superseded by the use of `across()`. The recipes step `step_mutate_at()` is still "active" but we have an [open recipes issue](https://github.com/tidymodels/recipes/issues/662) to decide what we do with that so maybe you don't want to put it so prominently in the book?

**Comment by juliasilge** [comment]
We might consider that section a place to offer some advice about when to include a transformation within a recipe and when to do it before/outside a recipe. We aren't getting rid of `step_mutate()` of course but our general advice is to use recipes for _learned_ transformations that you estimate from training data and apply to testing data. It may well be easier to do more straightforward transformations with another tool, like dplyr.
