### ISSUE TITLE
Use new `extract_*()` generics

### ISSUE THREAD

**Issue by hfrick** [tidymodels/TMwR#166]
I came across two places where the new `extract_*()` generics would be nice (this is not an exhaustive list):

- section 7.2: replace `pluck("fit")` with `extract_fit_engine()`
- chapter 8:  `pull_workflow_prepped_recipe()` and `pull_workflow_fit()`

**Comment by juliasilge** [comment]
Based on my grep-ing, I believe we have found all these. 👍
