### ISSUE TITLE
typos in the book

### ISSUE THREAD

**Issue by ChrisHH** [tidymodels/TMwR#167]
Hi, I spotted some typos in the book, listed below.

**Chapter 5.1**
`intial_split()` --> `initial_split()`

**Chapter 6.2**
(at the end)

`terms` --> `term`

**Chapter 7.1**
Is the previously mentioned section on PCA **8.4.4** (which is actually after at that point)?

**Chapter 10.1**
The function **estimate_perf(rf_fit, ames_test)** gives an rmse of **0.0810** (following the output); but the text below says it is **0.0695** (and much worse than the rmse from the training set). Note that 0.0695 is also shown in the table at the end of the chapter.

**Comment by juliasilge** [comment]
Thanks for the careful reading here @ChrisHH! 🙌
