### ISSUE TITLE
How open is the contribution channel?

### ISSUE THREAD

**Issue by PathosEthosLogos** [tidymodels/TMwR#174]
I'm interested in contributing.

I wanted to at least start on section 20 Ensemble Models, but it seems that it is already in progress.

I would also like to contribute to a new time series section, and request a Shiny section (I would like to contribute to Shiny section as well, but I'm learning it right now with difficulties, so it would require good amount of help/mentoring). I'm just not sure if adding new package (like Shiny) ought to be avoided as mentioned in contributing.md or the vision of the book is already set by the co-authors.

**Comment by topepo** [comment]
The table of contents is finalized so I don't think that we'll be adding more chapters any more. Feel free to put in pull requests for comments and/or edits though.
