### ISSUE TITLE
Section 9,2 refer back to Section 7.7

### ISSUE THREAD

**Issue by davestr2** [tidymodels/TMwR#179]
The second paragraph in Section 9.2 reads s:

"To illustrate, let’s take the model from Section 7.7. The lm_wflow_fit object was a linear regression model whose predictor set was supplemented with an interaction and spline functions for longitude and latitude. It was created from a training set (named ames_train"

I believe this should refer to Section 8.4.3 (Spline Functions). 

Section 7,7 is the Chapter Summary for that chapter, which is before the discussion on Splines.

**Comment by juliasilge** [comment]
Thanks so much for the careful reading and report @davestr2! 🙌

**Comment by davestr2** [comment]
Looks like may need the same thing done to the first line in Section 10.1. Maybe one reference change can fix both, if needed!

**Comment by juliasilge** [comment]
Yep, you are right! I did a search to find any other places we are using that workflows summary reference and the rest look correct.
