### ISSUE TITLE
different ensemble results between local and GHA

### ISSUE THREAD

**Issue by topepo** [tidymodels/TMwR#193]
Locally, my results for the first blending has: 

![image](https://user-images.githubusercontent.com/5731043/132951676-f99ef5f3-1ee9-4871-8861-dc3dc6913183.png)

GHA has: 

![image](https://user-images.githubusercontent.com/5731043/132951688-4ee62ec9-1209-40d9-a9d4-89961700b10d.png)

The racing results from the screening chapter are the substrate and those results match.

**Comment by juliasilge** [comment]
Here is what _I_ get locally for the first ensemble, different from both above:

![julias_ens](https://user-images.githubusercontent.com/12505835/133181760-b8c5d8a9-2b38-4cd3-be21-650d260835bc.png)

**Comment by juliasilge** [comment]
I now see this for the first ensemble, much closer to what is on GH actions but not exactly the same:

![stacks](https://user-images.githubusercontent.com/12505835/151429766-ee5eb41f-6e46-4072-a3ad-3789242386fc.png)

The next ensemble is a bit more different:

![stacks2](https://user-images.githubusercontent.com/12505835/151430007-b30cfcea-290c-4d35-ab8f-4b74ac8d32a1.png)

I don't get the same number retained (six instead of eight):

```
> ens
── A stacked ensemble model ─────────────────────────────────────

Out of 18 possible candidate members, the ensemble retained 6.
Penalty: 0.01.
Mixture: 1.

The 6 highest weighted members are:
# A tibble: 6 × 3
  member                    type          weight
  <chr>                     <chr>          <dbl>
1 boosting_1_19             boost_tree    0.620 
2 Cubist_1_25               cubist_rules  0.195 
3 neural_network_1_13       mlp           0.106 
4 CART_1_05                 decision_tree 0.0599
5 full_quad_linear_reg_1_16 linear_reg    0.0250
6 full_quad_linear_reg_1_17 linear_reg    0.0163

Members have not yet been fitted with `fit_members()`.
```

**Comment by juliasilge** [comment]
Today I ran the book on my older, Intel-based Mac and I got the results we currently see on GH actions and for you locally @topepo:

```
> ens
── A stacked ensemble model ─────────────────────────────────────

Out of 18 possible candidate members, the ensemble retained 7.
Penalty: 0.01.
Mixture: 1.

The 7 highest weighted members are:
# A tibble: 7 × 3
  member                    type          weight
  <chr>                     <chr>          <dbl>
1 boosting_1_19             boost_tree    0.640 
2 Cubist_1_25               cubist_rules  0.231 
3 CART_1_05                 decision_tree 0.0580
4 full_quad_linear_reg_1_16 linear_reg    0.0317
5 full_quad_linear_reg_1_17 linear_reg    0.0306
6 CART_bagged_1_1           bag_tree      0.0200
# … with 1 more row

Members have not yet been fitted with `fit_members()`.
```

**Comment by juliasilge** [comment]
I ran again today on my newer, ARM-based Mac and in Ch 15 I see different results from nnet (the results from Ch 15 are what Ch 20 is based on):
![racing_rank](https://user-images.githubusercontent.com/12505835/152256819-310c7306-a9b9-4001-b5b0-65061a8e4ff1.png)

Notice that the RMSE is slightly worse. Do we know anything about differences based on architecture for nnet?

**Comment by topepo** [comment]
I did some searching last night and could not find other reports about this for `nnet`. I do not thing that contacting the maintainer would be fruitful.

**Comment by juliasilge** [comment]
Many thanks to @hfrick for checking through this as well. Her results on her local ARM Mac are consistent with mine:

**We see different results for the nnet package on Intel vs. ARM architecture.**

It's good to know that much at least. Still outstanding to do/decide:

- do we want to call this out in the book, like in a footnote?
- do we want to take any steps to escalate the nnet issue to anyone?

**Comment by topepo** [comment]
> do we want to call this out in the book, like in a footnote?

Yes
