### ISSUE TITLE
Building 10-resampling.Rmd in Windows requires package doMC which does not appear to be supported

### ISSUE THREAD

**Issue by draziraphale** [tidymodels/TMwR#201]
## The problem

I'm having trouble building the book on Windows as part of it calls for the package **doMC** and [the corresponding Windows binary for the package doMC](https://cran.r-project.org/package=doMC) does not appear to exist on CRAN. If this is in fact a missing feature which means that the part of the book covered by the file **10-resampling.Rmd** is not available for Windows and not a bug, my apologies, I will close the bug and raise a feature request, but as it stands I am not certain.

## Reproducible example

```r
bookdown::render_book("index.Rmd", "bookdown::gitbook")
```
the code executes to until this point, where **doMC** is required and then halts...
.
.
.
.
processing file: 10-resampling.Rmd
  |.                                                                         |   1%
label: resampling-setup (with options) 
List of 1
 $ include: logi FALSE

Quitting from lines 2-12 (10-resampling.Rmd) 
Error in library(doMC) : there is no package called 'doMC'
Calls: local ... withCallingHandlers -> withVisible -> eval -> eval -> library

Execution halted
Error in Rscript_render(f, render_args, render_meta, add1, add2) : 
  Failed to compile 10-resampling.Rmd

### My session info
When I run **sessioninfo::sessionInfo()**, you can see the Windows environment I trying to run from, in case this is relevant.
sessioninfo::session_info()
#> - Session info ---------------------------------------------------------------
#>  setting  value                       
#>  version  R version 4.1.1 (2021-08-10)
#>  os       Windows 10 x64              
#>  system   x86_64, mingw32             
#>  ui       RTerm                       
#>  language (EN)                        
#>  collate  English_Ireland.1252        
#>  ctype    English_Ireland.1252        
#>  tz       Europe/London               
#>  date     2021-09-29                  
#> 
#> - Packages -------------------------------------------------------------------
#>  package     * version date       lib source        
#>  backports     1.2.1   2020-12-09 [1] CRAN (R 4.1.0)
#>  bookdown      0.24    2021-09-02 [1] CRAN (R 4.1.1)
#>  cli           3.0.1   2021-07-17 [1] CRAN (R 4.1.0)
#>  clipr         0.7.1   2020-10-08 [1] CRAN (R 4.1.0)
#>  crayon        1.4.1   2021-02-08 [1] CRAN (R 4.1.0)
#>  digest        0.6.27  2020-10-24 [1] CRAN (R 4.1.0)
#>  ellipsis      0.3.2   2021-04-29 [1] CRAN (R 4.1.0)
#>  evaluate      0.14    2019-05-28 [1] CRAN (R 4.1.0)
#>  fansi         0.5.0   2021-05-25 [1] CRAN (R 4.1.0)
#>  fs            1.5.0   2020-07-31 [1] CRAN (R 4.1.0)
#>  glue          1.4.2   2020-08-27 [1] CRAN (R 4.1.0)
#>  highr         0.9     2021-04-16 [1] CRAN (R 4.1.0)
#>  htmltools     0.5.1.1 2021-01-22 [1] CRAN (R 4.1.0)
#>  knitr         1.34    2021-09-09 [1] CRAN (R 4.1.1)
#>  lifecycle     1.0.0   2021-02-15 [1] CRAN (R 4.1.0)
#>  magrittr      2.0.1   2020-11-17 [1] CRAN (R 4.1.0)
#>  pillar        1.6.2   2021-07-29 [1] CRAN (R 4.1.0)
#>  pkgconfig     2.0.3   2019-09-22 [1] CRAN (R 4.1.0)
#>  purrr         0.3.4   2020-04-17 [1] CRAN (R 4.1.0)
#>  reprex        2.0.1   2021-08-05 [1] CRAN (R 4.1.0)
#>  rlang         0.4.11  2021-04-30 [1] CRAN (R 4.1.0)
#>  rmarkdown     2.11    2021-09-14 [1] CRAN (R 4.1.1)
#>  rstudioapi    0.13    2020-11-12 [1] CRAN (R 4.1.0)
#>  sessioninfo   1.1.1   2018-11-05 [1] CRAN (R 4.1.0)
#>  stringi       1.7.3   2021-07-16 [1] CRAN (R 4.1.0)
#>  stringr       1.4.0   2019-02-10 [1] CRAN (R 4.1.0)
#>  styler        1.5.1   2021-07-13 [1] CRAN (R 4.1.0)
#>  tibble        3.1.3   2021-07-23 [1] CRAN (R 4.1.0)
#>  utf8          1.2.2   2021-07-24 [1] CRAN (R 4.1.0)
#>  vctrs         0.3.8   2021-04-29 [1] CRAN (R 4.1.0)
#>  withr         2.4.2   2021-04-18 [1] CRAN (R 4.1.0)
#>  xfun          0.25    2021-08-06 [1] CRAN (R 4.1.0)
#>  yaml          2.2.1   2020-02-01 [1] CRAN (R 4.1.0)
#> 
#> [1] C:/Users/pdenny/Documents/R/R-4.1.1/library

**Comment by juliasilge** [comment]
You are right that the code for the book uses doMC:

https://github.com/tidymodels/TMwR/blob/78b09568c089d5f452bebd3a86cb2cb96f28bbb5/10-resampling.Rmd#L4

We are currently [building the book on a macOS machine](https://github.com/tidymodels/TMwR/blob/master/.github/workflows/bookdown.yaml) (and we personally use macOS machines locally when we build these chapters).

If you want to read about how to set up parallel processing on your own OS, check out [this section of the book](https://www.tmwr.org/resampling.html#parallel).

**Comment by draziraphale** [comment]
Thanks very much for that Julia, I will read the recommended section of the book. I will close the ticket, and after reading the relevant [book section that you pointed out](https://www.tmwr.org/resampling.html#parallel), it may make sense for me to request the support as a feature (subject of course to what you've put in that section of the book).
Thanks again, Patrick

**Comment by juliasilge** [comment]
The tune package itself works well on Windows (you can also read [about parallel processing here](https://tune.tidymodels.org/articles/extras/optimizations.html#parallel-processing-1)) but I don't believe we will maintain the book is such a way that it can build on any OS. The code you see rendered online at tmwr.org is general and not OS-specific but the code we use to build the book/website does depend on which OS we are building with.

**Comment by draziraphale** [comment]
Thanks for that ; I think that pursuing the tune package may be a good
route to directing the reader; I run in both Windows and Linux environments.
