### ISSUE TITLE
Dark mode 

### ISSUE THREAD

**Issue by psads-git** [tidymodels/TMwR#203]
I think it would be very convenient to have a button to turn on the dark mode -- the default white background hurts eyes, when reading for a long time.

Thanks in advance!

**Comment by psads-git** [comment]
For instance, the following book, by clicking on the icon "A", allows one to change to night mode:

https://bookdown.org/content/3686/

**Comment by juliasilge** [comment]
Related to #153 

As I outlined there, although we understand that there are folks like you who may prefer to use some of the font settings like night mode, we have heavily customized gitbook so much that it is not in scope for us to support these other modes, especially to the level of accessibility that we did with the basic mode. Much of the graphics work we did would also need to be adjusted for different modes such as a dark/night mode.

Thank you again for reading and for being interested in our project! 🙌
