### ISSUE TITLE
Book Font

### ISSUE THREAD

**Issue by asimumba** [tidymodels/TMwR#209]
Hi @topepo and @juliasilge ,
Thanks for your work on this book. I would like to get your thoughts on this suggestion. I find the font for the book a bit too small for comfortable reading. Is it possible to make it a bit bigger and probably also the line spacing?

**Comment by juliasilge** [comment]
Can you tell us more about the browser and OS you are using @asimumba? Maybe post a screenshot if something doesn't look right? We worked with a designer on the theme for our book who was careful to adhere to accessibility standards, including readability, font sizes, etc.

**Comment by juliasilge** [comment]
Thanks for your discussion, and let us know if you have further questions! 🙌
