### ISSUE TITLE
8.4.3 SPLINE FUNCTIONS. "plot_smoother" function

### ISSUE THREAD

**Issue by marcellodegiosa** [tidymodels/TMwR#210]
In the first chunk in section

8.4.3 SPLINE FUNCTIONS

when defining "plot_smoother" function,

"... y = Sale_Price)) +"  should be  "...y = 10^Sale_Price)) +"

MDG

**Comment by juliasilge** [comment]
We did purposefully plot this on the log scale actually; we don't want to plot the price on its original scale. Maybe we can make that more obvious with an axis label.
