### ISSUE TITLE
Fix x-axis label for posterior plot

### ISSUE THREAD

**Issue by topepo** [tidymodels/TMwR#227]
[These lines](https://github.com/tidymodels/TMwR/blob/main/11-comparing-models.Rmd#L386:L387) produce a bad label: 

![image](https://user-images.githubusercontent.com/5731043/152085899-ac0aa77a-f6c2-4742-820f-8e6bed0e5275.png)

(there is another before that). 

[This link](https://www.dataanalytics.org.uk/axis-labels-in-r-plots-using-expression/) led me to: 

``` r
x_lab <- expression(Posterior ~ "for" ~ mean ~ difference ~ "in" ~ R^2 ~ (splines + interaction - basic))

plot(1:2, xlab =  x_lab)
```

![](https://i.imgur.com/wllwTkS.png)

<sup>Created on 2022-02-01 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by juliasilge** [comment]
I'll go through and fix all the plots that use `expression()`.
