### ISSUE TITLE
Chapter 8 should use `remove_formula` instead of `remove_variables`?

### ISSUE THREAD

**Issue by GilHenriques** [tidymodels/TMwR#260]
Hi! This book is excellent. thank you so much for the work of writing it and for making it publicly available.

I'm working through the book and noticed that chapter 7 ends by explaining that the code used in later chapters is:

```r
lm_wflow <-  
  workflow() %>% 
  add_model(lm_model) %>% 
  add_formula(Sale_Price ~ Longitude + Latitude)
```

But in Chapter 8, section 8.2 explains how to attach a recipe to the workflow like this:

```r
lm_wflow <- 
  lm_wflow %>% 
  remove_variables() %>% 
  add_recipe(simple_ames)
```

I think this should be `remove_formula()`. 
I apologise if I'm mistaken.

**Comment by juliasilge** [comment]
Thanks for this report @GilHenriques! 🙌 

@topepo I think we should change the end of Ch 7 to use `add_variables()`. What do you think?
