### ISSUE TITLE
Ch 4 maps in grayscale

### ISSUE THREAD

**Issue by juliasilge** [tidymodels/TMwR#267]
The maps in Ch 4 need some changes for grayscale:

![Screen Shot 2022-03-16 at 5 10 27 PM](https://user-images.githubusercontent.com/12505835/158706208-14db0ca6-42f4-49dd-9012-94c79a06856b.png)

![Screen Shot 2022-03-16 at 5 10 37 PM](https://user-images.githubusercontent.com/12505835/158706216-4e2878dc-d01a-4ed5-88c5-7d508343e686.png)

I think the best thing to do might be to have all the houses the same shape and use `geom_text_repel()` to mark centers? Or do you have another strategy @topepo?

These changes will _not_ go to the website so you can put them in the `figs-for-print` branch that's (wrongly) a PR right now.

**Comment by juliasilge** [comment]
If we can fix this plot in Ch 19 too (not only for print) that would be great:

![](https://www.tmwr.org/figures/ap-autoplot-1.png)

DISTANCE DISTANCE

**Comment by topepo** [comment]
Color changes in #231

**Comment by juliasilge** [comment]
This is all closed except the applicable plot. 👍
