### ISSUE TITLE
Chapter 8 fail to update_role

### ISSUE THREAD

**Issue by ChandlerBBT** [tidymodels/TMwR#295]
## The problem

I'm having trouble with book code of chapter 8, seems `ames_rec` have no such a column: address

## Reproducible example

```r
ames_rec %>% update_role(address, new_role = "street address")
```
Error in `chr_as_locations()`:
! Can't subset columns that don't exist.
x Column `address` doesn't exist.
Backtrace:
  1. ames_rec %>% update_role(address, new_role = "street address")
  2. recipes::update_role(., address, new_role = "street address")
  3. recipes::recipes_eval_select(terms, data, info)
  4. tidyselect::eval_select(expr = expr, data = data, allow_rename = allow_rename_compat)
  5. tidyselect:::eval_select_impl(...)
     ...
 17. tidyselect:::reduce_sels(node, data_mask, context_mask, init = init)
 18. tidyselect:::walk_data_tree(new, data_mask, context_mask)
 19. tidyselect:::as_indices_sel_impl(...)
 20. tidyselect:::as_indices_impl(x, vars, call = call, strict = strict)
 21. tidyselect:::chr_as_locations(x, vars, call = call)

**Comment by juliasilge** [comment]
Yes, that's right. Notice [what we say here](https://www.tmwr.org/recipes.html#column-roles):

> For example, in our Ames data set, the original raw data contained a column for address.

And then the footnote:

> Our version of these data does not contain that column.

The version of the data used in this book does not contain that column; the idea of the original variable is being presented as a hypothetical use case for `update_role()`.
