### ISSUE TITLE
Chapter 16 typos and duplicate code chunks

### ISSUE THREAD

**Issue by gunnergalactico** [tidymodels/TMwR#301]
Online version of book.

chapter 16.1 reads:

"16.1 WHEN PROBLEMS CAN DIMENSIONALITY REDUCTION SOLVE?"

16.5.1 Principal Component Analysis repeats a code chunk.

"bean_rec_trained %>%
  step_pca(all_numeric_predictors(), num_comp = 4) %>%
  plot_validation_results() + 
  ggtitle("Principal Component Analysis")"

16.5.2 Partial Least Squares repeats a code chunk.

"bean_rec_trained %>%
  step_pls(all_numeric_predictors(), outcome = "class", num_comp = 4) %>%
  plot_validation_results() + 
  ggtitle("Partial Least Squares")"

16.5.3 Independent Component Analysis

"bean_rec_trained %>%
  step_ica(all_numeric_predictors(), num_comp = 4) %>%
  plot_validation_results() + 
  ggtitle("Independent Component Analysis")"

16.5.4 UNIFORM MANIFOLD APPROXIMATION AND PROJECTION repeats code chunk

"library(embed)
bean_rec_trained %>%
  step_umap(all_numeric_predictors(), num_comp = 4) %>%
  plot_validation_results() +
  ggtitle("UMAP")"

"bean_rec_trained %>%
  step_umap(all_numeric_predictors(), outcome = "class", num_comp = 4) %>%
  plot_validation_results() +
  ggtitle("UMAP (supervised)")"

Thank you for all your hard work.

**Comment by juliasilge** [comment]
Can you give us a little more info about the problems you are seeing? I believe this is as intended. Notice that the PCA section uses `step_pca()`, the PLS section uses `step_pls()`, and so forth.

**Comment by gunnergalactico** [comment]
[16 - reprex.pdf](https://github.com/tidymodels/TMwR/files/8696441/16.-.reprex.pdf)

Attached is a screenshot, not sure if it's my browser. I use safari and chrome

**Comment by juliasilge** [comment]
Ah, I see what you're saying now. Thank you so much! 🙌
