### ISSUE TITLE
Tag Print Version?

### ISSUE THREAD

**Issue by jonthegeek** [tidymodels/TMwR#314]
You might already be planning to do this, but, if it isn't too late, would it be possible to create a tag with the print version? It's helpful to be able to ~easily identify what has changed since the print version when we're running a book club and some are using print versions and some are using the latest online version.

**Comment by juliasilge** [comment]
FWIW there will be some differences from what is in the main branch from the print version, because in some chapters we changed animations to static plots, etc.

**Comment by jonthegeek** [comment]
That makes sense! It will be helpful to also include that note in the print-version tag description. Thanks!

**Comment by juliasilge** [comment]
We did two [releases](https://github.com/tidymodels/TMwR/releases) today, for the official "first edition" of the online and print versions.
