### ISSUE TITLE
Suggestion to improve code in TMwR where parallel processing is involved

### ISSUE THREAD

**Issue by bhattmaulik** [tidymodels/TMwR#320]
I was trying to knit the gitbook version of the book TMwR, but I was unable to. I am using a Windows system, and doMC package doesn't work on it. In the later chapters (like Chapter 15 of workflow-sets) there is a code so that it can work on both, Windows and non-Windows system. However, this code, which involves using grepl function and R.Version()$platform to decide whether this system has Windows or any other operating system, it was not working on my laptop. 
When I write in console `R.Version()$platform`, the output is `"x86_64-w64-mingw32"`. So, I changed the code as follows:

```
cores <- parallel::detectCores()
if(Sys.info()['sysname']=="Windows"){
   library(doParallel)
   cl <- makePSOCKcluster(cores)
   registerDoParallel(cl)
}else {
   library(doMC)
   registerDoMC(cores = cores)
}
```
After this change, the code is working now.

**Comment by juliasilge** [comment]
Thank you so much for reading @bhattmaulik! 🙌 This is related to #201, and I'll share again what we said there:

> The tune package itself works well on Windows (you can also read [about parallel processing here](https://tune.tidymodels.org/articles/extras/optimizations.html#parallel-processing-1)) but I don't believe we will maintain the book in such a way that it can build on any OS. The code you see rendered online at tmwr.org is general and not OS-specific but the code we use to build the book/website does depend on which OS we are building with.

We are committed to the book having code you read that works on all OSes, but not to building the book in such a way that it can be automatically built on all OSes.
