### ISSUE TITLE
Possible typo/error in text 

### ISSUE THREAD

**Issue by woodspock** [tidymodels/TMwR#323]
In chapter 8.4.1, juste after Figure 8.1, text says : 

_Here we see that two neighborhoods have less than five properties in the **training data** (Landmark and Green Hills); in this case, no houses at all in the Landmark neighborhood were included in the **training set**._

if I'm not wrong, I think it should be : 

_Here we see that two neighborhoods have less than five properties in the training data (Landmark and Green Hills); in this case, no houses at all in the Landmark neighborhood were included in the **testing** set.

**Comment by juliasilge** [comment]
Yep, you are right!

``` r
library(tidymodels)
data(ames)
ames <- mutate(ames, Sale_Price = log10(Sale_Price))

set.seed(502)
ames_split <- initial_split(ames, prop = 0.80, strata = Sale_Price)
ames_train <- training(ames_split)
ames_test  <-  testing(ames_split)

ames_train %>% count(Neighborhood) %>% filter(Neighborhood == "Landmark")
#> # A tibble: 1 × 2
#>   Neighborhood     n
#>   <fct>        <int>
#> 1 Landmark         1
ames_test %>% count(Neighborhood) %>% filter(Neighborhood == "Landmark")
#> # A tibble: 0 × 2
#> # … with 2 variables: Neighborhood <fct>, n <int>
#> # ℹ Use `colnames()` to see all variable names
```

<sup>Created on 2022-08-10 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

I have submitted this [as an errata at O'Reilly](https://www.oreilly.com/catalog/errata.csp?isbn=0636920674580) and will do a little PR here.
