### ISSUE TITLE
Errata for the physical book... Text is missing on page 64

### ISSUE THREAD

**Issue by RaymondBalise** [tidymodels/TMwR#326]
I am looking at the first printing of the physical book and the end of page 64 and the start of 65 was confusing.  In looking here I see that a sentence is missing at the bottom of page 64:

```
 2. Specify the engine for fitting the model
 ```

Without it the last paragraph on that page and mention of "three cases we outlined" mentioned on the next page is confusing.

Is there an errata page for the book or is is this the place to report issues?   

PS If  you need a detail oriented copy editor and r programer for the next edition, I am willing to work for hex stickers.  :)

**Comment by juliasilge** [comment]
Wow, you are right! Thanks for the report. That somehow got mangled; it is correct in the online work.

I have [submitted this as errata](https://www.oreilly.com/catalog/errata.csp?isbn=0636920674580); you'll see it there as unconfirmed for now until it goes through the system.
