### ISSUE TITLE
Clean up the branches? Which is the dev branch?

### ISSUE THREAD

**Issue by PathosEthosLogos** [tidymodels/TMwR#345]
It would be nice to know which are the official branches in the documentation.

**Comment by juliasilge** [comment]
The `main` branch is the default, and [what you see online](https://www.tmwr.org/) is published from that; the print book is modestly different and that content isn't reflected in full anywhere here on GitHub. 

Is there something specific you are looking for? We aren't likely to start deleting these branches in the near term.
