### ISSUE TITLE
maybe a typo in Fig 12.2 in Chapter 12.3

### ISSUE THREAD

**Issue by jlxAtNovozymes** [tidymodels/TMwR#357]
Hi, I'm not stat guy, when l look at this plot, caption under Fig 12.2 caught my attention. I guess the number should be 95% not 90%?. is that true?
![image](https://user-images.githubusercontent.com/90908083/226080918-a81c9fe7-2449-4556-ad65-7c311bdf99af.png)

**Comment by jlxAtNovozymes** [comment]
I'm not sure about the standard error computation is right or not. I guess standard error is standard deviation divided by square root of number, not the number. it's still in Chapter 12.3
![image](https://user-images.githubusercontent.com/90908083/226083897-21379861-414c-4e5b-952e-400927718d7b.png)

**Comment by juliasilge** [comment]
I believe we've got it correct on the first part of your question:

``` r
## 95% conf interval:
qnorm(.025, lower.tail=FALSE)
#> [1] 1.959964

## 90% conf interval:
qnorm(.05, lower.tail=FALSE)
#> [1] 1.644854
```

<sup>Created on 2023-04-04 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by topepo** [comment]
> I guess standard error is standard deviation divided by square root of number, not the number

That is correct. We'll fix that.
