### ISSUE TITLE
Port book to bs4 or quarto book

### ISSUE THREAD

**Issue by olivroy** [tidymodels/TMwR#365]
Are there any plans to change the book format to quarto or to bookdown bs4 book format?

Thanks for the great content !

**Comment by juliasilge** [comment]
We don't have current plans for that, no. We might do this if we take on a big update (like the tidymodels team is currently doing for <https://www.tidymodels.org/>, or I have done [for _Text Mining with R_ a while ago](https://www.tidytextmining.com/index.html)) but we don't plan to make those kinds of updates in the near future.

**Comment by juliasilge** [comment]
Let us know if you have further questions @olivroy!
