### ISSUE TITLE
standard error or standard deviation in Figure 14.3?

### ISSUE THREAD

**Issue by ayueme** [tidymodels/TMwR#373]
Hello there,
   I'm learning tidymodels by reading your book: Tidymodeling with R. I'm confused when read chapter 14.2.2(ACQUISITION FUNCTIONS), when explain figure 14.3, you said:

For these data, the GP model fit is shown in Figure 14.3. The shaded region indicates the mean  ±1 standard error. The two vertical lines indicate two candidate points that are examined in more detail later.

I think the "standard error" here should be "standard deviation".

**Comment by juliasilge** [comment]
Can you say more about why you think that @ayueme? We feel pretty confident that the caption is correct.

**Comment by ayueme** [comment]
> Can you say more about why you think that @ayueme? We feel pretty confident that the caption is correct.

Sorry to borther you, I got it. You are right. I suddenly understand why it should be standard error!
Whatever, Tnanks really much for your replying. I'll close the issue.
