### ISSUE TITLE
Render consistently fails in 14-iterative-search.Rmd

### ISSUE THREAD

**Issue by wehrv** [tidymodels/TMwR#375]
## The problem

Following the directions in the Readme for rendering this book, on my Mac Studio using Rstudio Server, I consistently get the below failure:

processing file: 14-iterative-search.Rmd
                                                                                                                               
Error in `verify_consistent_bo()`:
! These Bayesian optimization results don't match the previous values.:
Component "cost": Mean relative difference: 0.3666
Backtrace:
 1. global verify_consistent_bo(collect_metrics(svm_bo_sshh$result))

Quitting from lines 381-418 [iterative-cells-bo-calcs] (14-iterative-search.Rmd)
Execution halted
Error in Rscript_render(f, render_args, render_meta, add1, add2) : 
  Failed to compile 14-iterative-search.Rmd
Calls: local ... <Anonymous> -> render_new_session -> Rscript_render
Execution halted
Error: bookdown::render_book() failed to render the output format 'bookdown::gitbook'.
Execution halted

Exited with status 1.

**Comment by davidrsch** [comment]
Hello @wehrv I facet that issue myself when trying rendering the book local, please check #362

**Comment by wehrv** [comment]
Thank you David.  It certainly appears to be the same issue as commenting out the problematic line allows 14 to complete, and I guess from the previous thread it's going to be awhile as the remainder renders.  I'll close this issue as a duplicate.  Really appreciate the help.
