### ISSUE TITLE
Unable to toggle/show table of contents/navbar on mobile devices

### ISSUE THREAD

**Issue by mattwarkentin** [tidymodels/TMwR#60]
Hi,

I just wanted to let you know that the navbar is hidden on medium to small mobile devices. When viewing on my iPhone, the navbar was hidden by default and the only way I was able to navigate sections was by scrolling to the bottom of the page and clicking the __>__ arrow. This make the mobile experience a little less fun, since its hard to quickly navigate to certain sections.

In testing using the Google Chrome inspector, it seems like on screens ~<550px wide the navbar is hidden off to the right. Probably just need an extra media query to keep the navbar from wrapping around the right side on smaller screens, maybe best to keep it along the top. Hope this is helpful!

![tmwr](https://user-images.githubusercontent.com/27825069/93484339-c9749180-f8cf-11ea-8d52-69efadf299b0.gif)

**Comment by juliasilge** [comment]
@dcossyleon Do you think you could take a look at this when you get a chance?
