### ISSUE TITLE
Confusing box-text and example pair in fit (7.2 / 7.3)

### ISSUE THREAD

**Issue by Bijaelo** [tidymodels/TMwR#64]
The book seems well written and concise. While going through it I stumbled over a slightly confusing section with Fit however.  
For references I am reading the current (as of 2020-09-18) version of the book [online](https://www.tmwr.org/models.html). 

In a box in section 7.2 (Use the model results) there is a box stating
> Never pass the fit element of a parsnip model to a model prediction function; see Section 7.3 for making predictions. If the data were preprocessed in any way, incorrect predictions will be generated (sometimes, without errors). The underlying model’s prediction function has no idea if any transformations have been made to the data prior to running the model.

and then following the link for section 7.3 the example shows (quite correctly) that one simply uses `predict` to make predictions, with a slightly altered syntax (new_data rather than newdata). For new (and even experienced) users of R, which might not be used to using `S3` functions directly (eg. `predict.lm`). 

It feels like the distinction isn't immediately clear, and that it could be made clear by adding a small example such as in the example below:
> Never pass the fit element of a parsnip model to a model prediction function (for example `predict.lm` for models fit using `lm`); see Section 7.3 for making predictions. If the data were preprocessed in any way, incorrect predictions will be generated (sometimes, without errors). The underlying model’s prediction function has no idea if any transformations have been made to the data prior to running the model.

**Comment by topepo** [comment]
It might be that having s specific callout might make this more clear: 

```r
# do this: 
predict(lm_form_fit)

# DON'T do this
predict(lm_form_fit$fit)
```

**Comment by Bijaelo** [comment]
Sounds reasonable. This makes it blatantly obvious that even with half a decade of experience it was not clear to me. :-)
