### ISSUE TITLE
Book seems to be down on netify

### ISSUE THREAD

**Issue by GrayAlex49** [tidymodels/TMwR#69]
I was reading and when I switched chapters I got a 404. Now I seem to be getting a 404 at the main address.

![Screenshot_20200919-231933.png](https://user-images.githubusercontent.com/8571038/93694226-d3181800-face-11ea-9a18-1dd5b659b329.png)

**Comment by juliasilge** [comment]
It's [just building right now](https://github.com/tidymodels/TMwR/runs/1139422961)!

I am merging some of the PRs in at what we hope is a time with low traffic. Things will be back up ASAP! 🚀

**Comment by GrayAlex49** [comment]
Oh awesome, thanks so much. I'm really enjoying it.
