### ISSUE TITLE
This code results in Error: Please pass a data set to `new_data`

### ISSUE THREAD

**Issue by bdhumb** [tidymodels/TMwR#74]
I have been following along the examples in RStudio and this line results in Error: Please pass a data set to `new_data`

https://github.com/tidymodels/TMwR/blob/f87ccf639715e4b9718f9f891223f36fe40a4f67/feature-engineering.Rmd#L139

I have recipes 0.1.13 installed.

**Comment by juliasilge** [comment]
This is a change in the [current development version of recipes](https://github.com/tidymodels/recipes/blob/master/NEWS.md), soon to go to CRAN. You can install from GitHub:

```r
devtools::install_github("tidymodels/recipes")
```

If you are unable to install packages from GitHub, you can use `juice()` instead of `bake()` with `new_data = NULL`.

**Comment by juliasilge** [comment]
Let us know if you have any more problems! 🙌

**Comment by bdhumb** [comment]
> Let us know if you have any more problems! 🙌

Yes, thanks - I tried to do the devtools thing but couldn't make it work and decided to just wait until it was on CRAN. Thanks again!
