### ISSUE TITLE
Chapter 10.2.1: "R is smart enough"

### ISSUE THREAD

**Issue by Bijaelo** [tidymodels/TMwR#76]
This is somewhat of a suggestion to add a "to see this try doing" in chapter 10.2.1. I fell right into the trap of thinking that the way the data is split one for each fold would be a memory issue. I spend about 20 minutes before reading the line that correctly states "R is smart enough" to not copy the `data.frame` ( at least before making changes to one of them ).

After reading it however, and knowing I had spent some time going back digging into R's documentation on memory usage, I felt that a small example or "try this" box would've been nice in this section. 

One could consider whether it might be illustrative for readers to add a notebox like
```` 
:::rmdnote
To see this try executing `pryr::object_size(vfold_cv(ames_train, v = k))` for different values of k.
:::
```` 
to make an illustrative example around [line 203](https://github.com/tidymodels/TMwR/blob/f87ccf639715e4b9718f9f891223f36fe40a4f67/resampling.Rmd#L203) in resampling.Rmd 

This is of course just a suggestion for consideration, and it may also just be redundant clutter.

**Comment by juliasilge** [comment]
Thanks so much for this point @Bijaelo! I think a footnote will be perfect for this. 👍
