### ISSUE TITLE
Add more exercises for reader to the end of sections/chapters

### ISSUE THREAD

**Issue by brshallo** [tidymodels/TMwR#78]
I think it would be helpful if TMwR had more exercises for the reader to complete at the end of sections / chapters. (There are some informal questions in the book, e.g. near end of ch 4, though I would prefer if this was more consistent and formal across the book.)

I liked that [R4DS](https://r4ds.had.co.nz/) included exercises... these made it easier for me to organize study group discussions around the book, e.g. [Yet another 'R for Data Science' study guide, ch 7](https://brshallo.github.io/r4ds_solutions/07-exploratory-data-analysis.html):
![image](https://user-images.githubusercontent.com/30487784/95241347-9e4cd600-07db-11eb-92c1-d768af81e8d5.png)

(Perhaps exercises from sources such as [juliasilge/supervised-ML-case-studies-course](https://github.com/juliasilge/supervised-ML-case-studies-course) could be repurposed for TMwR... or you could call on #rstats community to contribute appropriate exercises/questions, i.e. w/ "help wanted" tag.)

**Comment by juliasilge** [comment]
Thank you so much for this suggestion @brshallo! We are publishing a print version with O'Reilly and don't have this in our plan for the published version. We could definitely see a set of exercises in the future (perhaps created/curated by the community) in a separate repo, for example.
