### ISSUE TITLE
Failed when compiling PDF

### ISSUE THREAD

**Issue by albert-ying** [tidymodels/TMwR#84]
Hi, I was trying to compile a pdf book using

`bookdown::render_book("index.Rmd", "bookdown::pdf_book")`

However, it gives me the following error.

`output file: references.knit.md

/usr/local/bin/pandoc +RTS -K512m -RTS ./index.split.md ./software-modeling.split.md ./tidyverse.split.md ./base-r.split.md ./basics.split.md ./ames.split.md ./data-spending.split.md ./feature-engineering.split.md ./fitting-models.split.md ./the-model-workflow.split.md ./judging-model-effectiveness.split.md ./tools.split.md ./resampling.split.md ./comparing-models.split.md ./tuning-parameters.split.md ./grid-search.split.md ./iterative-search.split.md ./explaining-models.split.md ./appendix.split.md ./pre-proc-table.split.md ./references.split.md --to latex --from markdown+autolink_bare_uris+tex_math_single_backslash --output _main.tex --lua-filter /Library/Frameworks/R.framework/Versions/4.0/Resources/library/rmarkdown/rmarkdown/lua/pagebreak.lua --lua-filter /Library/Frameworks/R.framework/Versions/4.0/Resources/library/rmarkdown/rmarkdown/lua/latex-div.lua --self-contained --table-of-contents --toc-depth 2 --number-sections --highlight-style tango --pdf-engine pdflatex --natbib --include-in-header latex_extras/preamble.tex --variable graphics --wrap preserve --include-in-header /var/folders/hx/y7h1vl9d25q9mppm8kwh7t7m0000gp/T//Rtmpf9uDsS/rmarkdown-str1127068048479.html --variable tables=yes --standalone -Mhas-frontmatter=false --file-scope
! Missing $ inserted.
<inserted text>
                $
l.3884 <tt>lm_
              fit</tt> & 0.0744 & 0.0808\\

Error: LaTeX failed to compile _main.tex. See https://yihui.org/tinytex/r/#debugging for debugging tips. See _main.log for more info.
Please delete _main.md after you finish debugging the error.`

I'm wondering how to solve this, or whether it is possible for you to upload a pdf version of the book?

Thank you!

**Comment by juliasilge** [comment]
We're not currently supporting PDF at the time being! We expect knitting to HTML to work, however.

**Comment by albert-ying** [comment]
Thank you, Julia. I found a workaround that use `bookdown::render_book("index.Rmd", "bookdown::html_document2")` to create a single HTML and then print it in PDF, so I can read it on my ebook device.

Closing this issue.
