### ISSUE TITLE
Latex compilation errors and fixes

### ISSUE THREAD

**Issue by MaciekChudek** [tidymodels/TMwR#89]
There were numerous latex compilation errors when trying to compile to PDF with "bookdown::render_book("index.Rmd", "bookdown::pdf_book")". Specifically:

- Two instances of unescape underscores. Both fixed by changing `kable(escape = FALSE)` to `kable(escape = TRUE)`. 
  - 10-resampling.Rmd: 120
  - pre-proc-table.Rmd: 70
- `Package amsmath error: Erroneous nesting of equation structures;` caused by nesting an `{align}` environment inside an equation ( because $$...$$ compiles to \\[...\\]) in 11-comparing-models.Rmd: 230. I fixed this by removing the $$ tags, but this may break the HTML compilation so may not be a general solution.
- key `pvalue` multiply defined in bibliography. Fixed by removing entry at TMwR.bib: 329

Please note also that the table in pre-proc-table.Rmd overflows the PDF page, likely due to the manually inserted HTML \<tt\> tags. However this does not prevent compilation.

I would have included these as a pull request, but I haven't actually read the book yet so I'm not confident in my RMarkdown coding.

**Comment by topepo** [comment]
We have a lot of HTML-specific items in there; we don't plan on working on LaTeX/PDF targets until it is complete and we are working with a publisher. Until then, we only support HTML.

**Comment by juliasilge** [comment]
Also related to #84 

Since we're getting several questions about this, I'll add something to the README

**Comment by juliasilge** [comment]
Thanks for your discussion points @MaciekChudek! 🙌
